// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: lsm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys   [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Types  []byte   `protobuf:"bytes,3,opt,name=types,proto3" json:"types,omitempty"`
}

func (x *DataBlock) Reset() {
	*x = DataBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBlock) ProtoMessage() {}

func (x *DataBlock) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBlock.ProtoReflect.Descriptor instead.
func (*DataBlock) Descriptor() ([]byte, []int) {
	return file_lsm_proto_rawDescGZIP(), []int{0}
}

func (x *DataBlock) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *DataBlock) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DataBlock) GetTypes() []byte {
	if x != nil {
		return x.Types
	}
	return nil
}

type IndexBlockEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastKey []byte `protobuf:"bytes,1,opt,name=lastKey,proto3" json:"lastKey,omitempty"`
	Offset  uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size    uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Cached  bool   `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
}

func (x *IndexBlockEntry) Reset() {
	*x = IndexBlockEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexBlockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexBlockEntry) ProtoMessage() {}

func (x *IndexBlockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexBlockEntry.ProtoReflect.Descriptor instead.
func (*IndexBlockEntry) Descriptor() ([]byte, []int) {
	return file_lsm_proto_rawDescGZIP(), []int{1}
}

func (x *IndexBlockEntry) GetLastKey() []byte {
	if x != nil {
		return x.LastKey
	}
	return nil
}

func (x *IndexBlockEntry) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *IndexBlockEntry) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IndexBlockEntry) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type IndexBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstKey   []byte             `protobuf:"bytes,1,opt,name=firstKey,proto3" json:"firstKey,omitempty"`
	LastKey    []byte             `protobuf:"bytes,2,opt,name=lastKey,proto3" json:"lastKey,omitempty"`
	OriginSize uint32             `protobuf:"varint,3,opt,name=originSize,proto3" json:"originSize,omitempty"`
	Entries    []*IndexBlockEntry `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *IndexBlock) Reset() {
	*x = IndexBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lsm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexBlock) ProtoMessage() {}

func (x *IndexBlock) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexBlock.ProtoReflect.Descriptor instead.
func (*IndexBlock) Descriptor() ([]byte, []int) {
	return file_lsm_proto_rawDescGZIP(), []int{2}
}

func (x *IndexBlock) GetFirstKey() []byte {
	if x != nil {
		return x.FirstKey
	}
	return nil
}

func (x *IndexBlock) GetLastKey() []byte {
	if x != nil {
		return x.LastKey
	}
	return nil
}

func (x *IndexBlock) GetOriginSize() uint32 {
	if x != nil {
		return x.OriginSize
	}
	return 0
}

func (x *IndexBlock) GetEntries() []*IndexBlockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_lsm_proto protoreflect.FileDescriptor

var file_lsm_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6c, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x22, 0x4d, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x6f, 0x0a, 0x0f, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6c, 0x61, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x6c, 0x61, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x67, 0x7a, 0x6c, 0x75, 0x63, 0x61, 0x72,
	0x69, 0x6f, 0x2f, 0x4c, 0x53, 0x4d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lsm_proto_rawDescOnce sync.Once
	file_lsm_proto_rawDescData = file_lsm_proto_rawDesc
)

func file_lsm_proto_rawDescGZIP() []byte {
	file_lsm_proto_rawDescOnce.Do(func() {
		file_lsm_proto_rawDescData = protoimpl.X.CompressGZIP(file_lsm_proto_rawDescData)
	})
	return file_lsm_proto_rawDescData
}

var file_lsm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lsm_proto_goTypes = []interface{}{
	(*DataBlock)(nil),       // 0: cache.DataBlock
	(*IndexBlockEntry)(nil), // 1: cache.IndexBlockEntry
	(*IndexBlock)(nil),      // 2: cache.IndexBlock
}
var file_lsm_proto_depIdxs = []int32{
	1, // 0: cache.IndexBlock.entries:type_name -> cache.IndexBlockEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lsm_proto_init() }
func file_lsm_proto_init() {
	if File_lsm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lsm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexBlockEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lsm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lsm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lsm_proto_goTypes,
		DependencyIndexes: file_lsm_proto_depIdxs,
		MessageInfos:      file_lsm_proto_msgTypes,
	}.Build()
	File_lsm_proto = out.File
	file_lsm_proto_rawDesc = nil
	file_lsm_proto_goTypes = nil
	file_lsm_proto_depIdxs = nil
}
